FROM jenkins/jenkins:lts-jdk21

USER root

ARG HELM_VERSION=v3.19.0

RUN apt-get update \
    && apt-get install -y \
        ca-certificates \
        curl \
        git \
        gnupg \
        lsb-release \
        maven \
        tar \
    && rm -rf /var/lib/apt/lists/*

RUN install -m 0755 -d /etc/apt/keyrings \
    && curl -fsSL https://download.docker.com/linux/debian/gpg \
       -o /etc/apt/keyrings/docker.asc \
    && chmod a+r /etc/apt/keyrings/docker.asc \
    && echo \
       "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
       $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
       > /etc/apt/sources.list.d/docker.list \
    && curl -fsSL https://deb.nodesource.com/setup_22.x | bash - \
    && apt-get update \
    && apt-get install -y docker-ce-cli nodejs \
    && rm -rf /var/lib/apt/lists/*

RUN curl -fsSL \
      https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable/openshift-client-linux.tar.gz \
      -o /tmp/openshift-client.tar.gz \
    && tar -xzf /tmp/openshift-client.tar.gz \
       -C /usr/local/bin oc \
    && chmod +x /usr/local/bin/oc \
    && rm -f /tmp/openshift-client.tar.gz

RUN curl -fsSL \
      https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz \
      -o /tmp/helm.tar.gz \
    && tar -xzf /tmp/helm.tar.gz -C /tmp \
    && mv /tmp/linux-amd64/helm /usr/local/bin/helm \
    && chmod +x /usr/local/bin/helm \
    && rm -rf /tmp/helm.tar.gz /tmp/linux-amd64

RUN jenkins-plugin-cli --plugins \
    workflow-aggregator \
    git \
    credentials-binding \
    docker-workflow

USER jenkins